/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/Admin/Admin.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DataBlock: typeof import('./src/components/DataBlock.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MediaModal: typeof import('./src/components/MediaModal.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TitleBlock: typeof import('./src/components/TitleBlock.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.3_c89cb6a4e50f7de1b3c49f525a515918/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
